import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "../components/Provider";
import { cookies } from "next/headers";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  Private,
  Public,
}: Readonly<{
  Private: ReactNode;
  Public: ReactNode;
}>) {
  const cookieStorage = await cookies();
  const cookie = cookieStorage.get("go-barber-cookie")?.value;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>{!!cookie ? Private : Public}</Provider>
      </body>
    </html>
  );
}
